import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import HeaderTop from '@/Components/HeaderTop';
import HeaderMiddle from '@/Components/HeaderMiddle';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<>
			<html lang="en">
				<header>
					<div className="container">
						<HeaderTop />
						<HeaderMiddle />
					</div>
				</header>
				<main>{children}</main>
				<footer></footer>
			</html>
		</>
	);
}
